### ISSUE TITLE
Samtalestøtten er flyttet - oppdater lenke 

### ISSUE THREAD

**Issue by runska** [navikt/oppfolgingsplan-frontend#275]
Heisann, samtalestøtten er fjernet som egen applikasjon og flyttet til EnonicXP. 

Ny URL er https://www.nav.no/arbeidsgiver/samtalestotte-arbeidsgiver

Relatert kodelinje: 
https://github.com/navikt/oppfolgingsplan-frontend/blob/fcedc52b91d35dd7ea96f02e038fce5c13d8183f/src/components/blocks/samtalestotte/SamtaleStotte.tsx#L20C90-L20C90

(referer-parameteren kan fjernes)

**Comment by AudunSorheim** [comment]
@runska Fikset i https://github.com/navikt/oppfolgingsplan-frontend/pull/278
